name: Hypatia Masnion
favicon: null
layout_spectrum: 0.410322712501511
typography_spectrum: 0.8942840304225683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8343479277100414
  lightness: 0.31196740362793207
  saturation: 0.9754908916074783
  rhythmicContrast: 0.9744694384280592
purpose: []
