name: Hypatia Masnion
favicon: null
layout_spectrum: 0.410322712501511
typography_spectrum: 0.8942840304225683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dec6ac'
    - '#28150f'
    - '#813819'
    - '#a86947'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
